### PR TITLE
Bps shunt resistor layout redesign

### PR DESCRIPTION
**Pull request by connorl309**
# Quality Assurance Checklist
To make reviews more efficient, please make sure the board meets the following standards and check everything off once the board meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._

There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions.

### Minimum Prerequisites
- [X] Pushed changes to branch.
- [X] The board passes ERC and DRC.
    - Note some ERC warnings are acceptable.
- [X] All traces are routed.
- [X] Units are in metric.

### 2D Spacing
- [X] The components are spaced out at an optimal distance.
    - All components can be easily hand-soldered.
    - IPC-SM-782A Standard requires a minimum distance of 1.0mm from edge to edge.
- [X] Components that are in parallel with each other are spaced out at an equal distance when possible.
- [X] The components are aligned with each other when possible.
- [X] Components are grouped based off of functionality.
    - E.g. all components for CAN should be grouped.
- [X] Bypass capacitors are less than 1cm away from their respective IC's power pins.

### 3D Spacing
- [X] Layout of components have been placed with mounting location and usage of the board in mind.
    - Are PCBs going to be stacked on above/below this board? Are tall components placed accordingly?
    - Are buttons and lights easily accessible and viewable?
    - When mounted into the car, are the heights of the components and connectors accounted for?
- [X] Location of connectors and wires going out of the board will prevent messy wiring.
    - Are all the wires that are going in the same direction placed on the same edge of the board?

### Components
- [X] Custom footprints have been double checked with the datasheet.
- [X] Pin 1 of the footprint is labeled in some way.

### Copper Layer
- [X] The trace widths and trace clearances are greater than JLCPCB's minimum requirements.
- [X] The trace lengths are as short as possible.
    - Can there be a more optimal route if you go to another layer?
- [X] Each trace's width is capable of handling the expected current flow.
    - Use PCB width calculator to calculate trace width.
- [X] *No sharp corners. No trace angles equal to or less than 90 degrees.
- [X] Traces are in parallel with each other when possible.
    - E.g. traces connected between an IC and MCU can be placed in parallel with each other.
- [X] There are no random trace appendages.
- [X] Vias placed in copper pads are fully encompassed in the copper pads.
- [X] Through-hole components do not have extraneous vias.

*Not really a problem for modern manufacturing techniques but good practice and important for high speed signal integrity.

### Silkscreen Layer
- [X] Visible text sizes are greater than JLCPCB's minimum requirements.
- [X] All visible text is on the silkscreen layer.
- [X] All reference labels of each component are not overlapping a copper pad or another component.
- [X] All connector pins are labeled with a meaningful and helpful name.
- [X] All LEDs are labeled with a meaningful and helpful name.

### Edge Cut Layer
- [X] The dimensions of the board and the mounting holes are nice values in metric i.e. no long decimals.
- [X] The physical outline of the board is on the edge cut layer.
- [X] Edge cuts are straight and parallel with opposite edge of the board.
- [X] Mounting holes are aligned.
- [X] Corners are curved and contoured to mounting holes.

### IMPORTANT NOTICE
- [X] I am confident that this board will be safe to use in a safety critical environment.
- [X] I had fun :)

## Other Comments
_Write any comments about the board that would help the reviewers here._

### CODE REVIEW

**Comment by connorl309** [comment]
I know there's a lot of commits sorry. Its so I could work on it at home and at workday.

image

**Review by pramukap — APPROVED** [review]

**Review by ray4477 — APPROVED** [review]
Looks good. I like the idea of just bypassing the weird connector altogether.

**Review by pramukap — COMMENTED** [review]
Looks good and the board's design corresponds with Connor's explanation of the board's function

**Comment by HannahSLee14** [comment]
I think your board looks good! Before submitting the purchase order, I would just double check all the measurements just one more time just in case. Also, feel free to put your name on it and to put this on it as well:
UTSVT - BPS
Shunt Resistor v.1.2 
Fall 2022
(You can correct it with the correct version number - this allows us to know which version this PCB is and when it was made, which is helpful when we have a lot of PCBs in storage at the moment.)

**Review by manthanand — APPROVED** [review]

**Pull request merged**
