### PR TITLE
Shunt redesign hat and taps

### PR DESCRIPTION
**Pull request by connorl309**
PCB file can be ignored. Schematic created. 

Net labels to allow voltage divider/shunt resistor to all work (hopefully).
Voltage divider stays separate from the shunt itself, but divides down to the shunt resistor voltage levels, such that we can route the voltage divider values directly into the current monitor and pretend like we're reading from across the shunt (when assembled,  the voltage divider won't be used at all.)

### CODE REVIEW

**Comment by manthanand** [comment]
image
Add datasheets for all components that are going to be on the boards. This will make it easier to determine a final BOM later on.

**Comment by manthanand** [comment]
image
Since this is going to be a hat above the current board, it might be necessary to have more than 2 mounting holes.

**Comment by manthanand** [comment]
image
Try keeping all the labels a consistent size. Also if it is unnecessary, it would be nicer to keep wires together instead of split up. You can still leave a label on the wire so it is easy to understand.

**Comment by manthanand** [comment]
Some of the Footprints for the components are inaccurate.

**Comment by connorl309** [comment]
Regarding the footprints, I cannot find footprints for the shunt resistor or the 4 pin connector. They are not in the UTSVT library. Hannah said that I could create a footprint for the shunt resistor following the [enclosure datasheet's A/B peg distances](https://www.vishay.com/docs/31094/wsbm8518.pdf), but if we aren't using the enclosure I am unsure which shunt resistor we are using or what the sizes for it will be.

**Comment by manthanand** [comment]
image
Is there really a point to this resistor?

**Comment by connorl309** [comment]
> 
Yes, that 1k resistor lets us divide down to 7mV, which if was going across the shunt resistor, would be measured around 70 amps.

**Comment by manthanand** [comment]
A footprint is what is used to actually determine the shape of the solder pads on the board. Since we already have a board with a shunt resistor on it, we should have a footprint that you can copy. I was discussing circuitry that you added (like J2/3)

**Comment by manthanand** [comment]
I would consider doing the math again on the resistor. A really small resistance in parallel with a really large resistance is just a really small resistance.

**Comment by connorl309** [comment]
> 

I was thinking the voltage divider is not connected to the shunt resistor, rather we have it separate, but both the shunt resistor and the voltage divider will connect into the current monitor IC. INA136 or something like that. That way we can just ignore the shunt resistor and use the voltage divider to emulate the shunt being in place, as the current monitor appears to just be monitoring the 100u voltage drop. 
image

**Comment by connorl309** [comment]
Also, the only 70k resistors Mouser "has" from Vishay aren't in stock. Is it acceptable to do a 50k and 20k in series or are we trying to minimize the amount of materials we use for this.

**Comment by manthanand** [comment]
According to the schematic, the 1k and 1u resistor are in parallel. I do not see how the 2 are separate from looking at the schematic or how we could implement ignoring the shunt resistor.

**Comment by connorl309** [comment]
> According to the schematic, the 1k and 1u resistor are in parallel. I do not see how the 2 are separate from looking at the schematic or how we could implement ignoring the shunt resistor.

Are there types of switches that pass through two connections? Like a mux for hardware? We could have a switch like this on the board that we flip towards the voltage divider or the actual shunt when it's needed. Although I can see that being potentially not allowed due to the current monitor relying on the switch to not fail, although it shouldn't fail for electrical reasons...

**Comment by manthanand** [comment]
For 70k Res, look for a value that is available that is close to what we want. Splitting in 2 isn't ideal.
For the second question, look up Single Pole Double Throw Switch. Though there is a better way of implementing this circuit without that.

**Comment by manthanand** [comment]
image
Make this a THT. Also add datasheet for it in description.

**Comment by manthanand** [comment]
Add some notes about what voltage corresponds to what current. Remove notes with all datasheets on bottom of schematic. Center entire schematic.

**Comment by manthanand** [comment]
image
Confirm that this matches with the connector on the Amperes Board.

**Comment by connorl309** [comment]
> image Confirm that this matches with the connector on the Amperes Board.

Won't be able to confirm this until Tianda works on the schematic redesign. I think we both agreed we'd use a 5 pin connector probably, but I'll need to talk to him at either the next meeting or on Slack to confirm

**Comment by manthanand** [comment]
Please rename this branch to a version name. Idk what the old version is, but if there isn't one, then start it off with 1.2.

**Pull request closed without merging**
